CREATE DATABASE AsegAutos

USE AsegAutos

CREATE TABLE Departamento(
IdDep INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomDep NVARCHAR(55) NOT NULL
)

CREATE TABLE Municipio(
IdMun INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomMun NVARCHAR(55) NOT NULL,
IdDep INT FOREIGN KEY REFERENCES Departamento(IdDep) NOT NULL
)

CREATE TABLE Marcas(
IdM INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomM NVARCHAR(25) NOT NULL,
DescM NVARCHAR(85) NOT NULL
)

CREATE TABLE Modelo(
IdMo INT PRIMARY KEY NOT NULL,
NombreMo NVARCHAR(15) NOT NULL,
DescMo NVARCHAR(15) NOT NULL
)

CREATE TABLE COLORES(
CodC NVARCHAR(15) PRIMARY KEY CHECK(CodC LIKE '%#') NOT NULL,
NomC NVARCHAR(25) NOT NULL
)

CREATE TABLE Clientes(
IdC INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FNC DATE NOT NULL,
PNC NVARCHAR(45) NOT NULL,
SNC NVARCHAR(45),
PAC NVARCHAR(45) NOT NULL,
SAC NVARCHAR(45),
SexoC CHAR(1) CHECK(SexoC LIKE '[F|M|f|m]') NOT NULL,
TelC CHAR(8) CHECK (TelC LIKE '[2|5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
IdMun INT FOREIGN KEY REFERENCES Municipio(IdMun) NOT NULL,
DirC NVARCHAR(125) NOT NULL
)

CREATE TABLE TipoAut(
IdTipo INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NomTipo NVARCHAR(35) NOT NULL,
CategT NVARCHAR(35) NOT NULL
)

CREATE TABLE Automovil(
Chasis NVARCHAR(25) PRIMARY KEY NOT NULL,
NMatri NVARCHAR(8) NOT NULL,
PotCo NVARCHAR(8) NOT NULL,
IdM INT FOREIGN KEY REFERENCES Marcas(IdM) NOT NULL,
IdMo INT FOREIGN KEY REFERENCES Modelo(IdMo) NOT NULL,
CodC NVARCHAR(15) FOREIGN KEY REFERENCES Colores(CodC) NOT NULL,
IdTipo INT FOREIGN KEY REFERENCES TipoAut(IdTipo) NOT NULL,
IdC INT FOREIGN KEY REFERENCES Clientes(IdC) NOT NULL
)

CREATE TABLE Taller(
IdT INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
UbicT NVARCHAR(150) NOT NULL,
NomT NVARCHAR(55) NOT NULL,
TelT CHAR(8) CHECK (TelT LIKE '[2|5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL
)

CREATE TABLE Seguros(
IdSeg INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
TipoSeg NVARCHAR(15) NOT NULL,
DescSeg NVARCHAR(150) NOT NULL,
Estado NVARCHAR(25) NOT NULL,
Vigencia DATE NOT NULL,
Chasis NVARCHAR(25) FOREIGN KEY REFERENCES Automovil(Chasis) NOT NULL,
IdT INT FOREIGN KEY REFERENCES Taller(IdT) NOT NULL
)

CREATE TABLE Pago(
IdPago INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
CantP FLOAT NOT NULL,
TipoP NVARCHAR(12) NOT NULL
)

CREATE TABLE Accidente(
CodAcc INT PRIMARY KEY NOT NULL,
RespAcc NVARCHAR(85),
TipoAcc NVARCHAR(55) NOT NULL,
FechaAcc DATE NOT NULL,
DescAcc NVARCHAR(150) NOT NULL,
Chasis NVARCHAR(25) FOREIGN KEY REFERENCES Automovil(Chasis) NOT NULL,
IdMun INT FOREIGN KEY REFERENCES Municipio(IdMun) NOT NULL,
IdPago INT FOREIGN KEY REFERENCES Pago(IdPago) NOT NULL
)

CREATE TABLE Afectados(
IdAf INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Gravedad NVARCHAR(25) NOT NULL,
PNA NVARCHAR(25) NOT NULL,
SNA NVARCHAR(25),
PAA NVARCHAR(25) NOT NULL,
SAA NVARCHAR(25),
CodAcc INT FOREIGN KEY REFERENCES Accidente(CodAcc) NOT NULL
)
