CREATE DATABASE ATUNDBPS2

USE ATUNDBPS2

CREATE TABLE Pais(
IdP CHAR(4) PRIMARY KEY NOT NULL,
NomP NVARCHAR(35) NOT NULL
)

CREATE TABLE Provincia(
IdPro CHAR(4) PRIMARY KEY NOT NULL,
NomPro NVARCHAR(35) NOT NULL,
IdP CHAR(4) FOREIGN KEY REFERENCES Pais(IdP) NOT NULL
)

CREATE TABLE Sucursal(
IdS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
DirS NVARCHAR(150) NOT NULL,
TelS CHAR(8) CHECK(TelS LIKE'[2|5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
IdPro CHAR(4) FOREIGN KEY REFERENCES Provincia(IdPro) NOT NULL
)

CREATE TABLE Turista(
CodT INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
PNT NVARCHAR(25) NOT NULL,
SNT NVARCHAR(25),
PAT NVARCHAR(25) NOT NULL,
SAT NVARCHAR(25),
IdPro CHAR(4) FOREIGN KEY REFERENCES Provincia(IdPro) NOT NULL,
TelT CHAR(8) CHECK(TelT LIKE'[2|5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL
)

CREATE TABLE ContratarSucursal(
NoCS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FecCS DATE NOT NULL,
CodT INT FOREIGN KEY REFERENCES Turista(CodT) NOT NULL,
IdS INT FOREIGN KEY REFERENCES Sucursal(IdS) NOT NULL
)

CREATE TABLE Hotel(
CodH CHAR(4) PRIMARY KEY NOT NULL,
NomH NVARCHAR(25) NOT NULL,
DirH NVARCHAR(150) NOT NULL,
TelH CHAR(8) CHECK(TelH LIKE'[2|5|7|8][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
NoP INT NOT NULL,
IdPro CHAR(4) FOREIGN KEY REFERENCES Provincia(IdPro) NOT NULL
)

-- DEFINIENDO QUE EL NUMERO DE PLAZAS TOTALES NO PUEDE SER MENOR A 0

CREATE RULE NPTH
AS
@V>=0

sp_bindrule 'NPTH','Hotel.NoP'

CREATE TABLE Reservacion(
IdR INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FecE DATE NOT NULL,
FecS DATE NOT NULL,
TipR CHAR(1) CHECK(TipR LIKE '[T|P|t|p]') NOT NULL,
Pension CHAR(1) CHECK(Pension LIKE'[M|C|m|c]')NOT NULL,
CodT INT FOREIGN KEY REFERENCES Turista(CodT) NOT NULL,
CodH CHAR(4) FOREIGN KEY REFERENCES Hotel(CodH) NOT NULL
)

CREATE TABLE TipoClaseVuelo(
IdC INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NomC NVARCHAR(25) NOT NULL
)

CREATE TABLE Vuelo(
NoV INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FecV DATE NOT NULL,
NoTV INT NOT NULL,
HorS TIME NOT NULL,
HorE TIME NOT NULL,
OrigV CHAR(4) FOREIGN KEY REFERENCES Provincia(IdPro) NOT NULL,
DestV NVARCHAR(25) NOT NULL,
)


-- DEFINIENDO QUE EL NUMERO DE VUELOS TOTALES NO PUEDE SER MENOR A 0

CREATE RULE NTV
AS
@V>=0

sp_bindrule 'NTV','Vuelo.NoTV'

CREATE TABLE CompraVuelo(
IdCom INT IDENTITY(1,1) NOT NULL,
FeC SMALLDATETIME NOT NULL,
NoV INT FOREIGN KEY REFERENCES Vuelo(NoV) NOT NULL,
CodT INT FOREIGN KEY REFERENCES Turista(CodT) NOT NULL,
IdC INT FOREIGN KEY REFERENCES TipoClaseVuelo(IdC) NOT NULL
)
